export const menuData = [
    {
        name: 'Makanan Indonesia (Indonesian Food)',
        items: [
            { name: 'Ayam Penyet Goreng', price: 30000 },
            { name: 'Ayam Bakar', price: 20000 },
            { name: 'Ayam Goreng Pop', price: 20000 },
            { name: 'Ayam Jingkrak', price: 30000 },
            { name: 'Ayam Penyet Bakar', price: 30000 },
            { name: 'Ayam Cabe Ijo', price: 30000 },
            { name: 'Ayam Goreng Mentega', price: 35000 },
            { name: 'Bebek Penyet Bakar', price: 40000 },
            { name: 'Bebek Penyet Goreng', price: 40000 },
        ]
    },
    {
        name: 'Nasi Goreng',
        items: [
            { name: 'Nasi Goreng Original', price: 30000 },
            { name: 'Nasi Goreng Kampung', price: 30000 },
            { name: 'Nasi Goreng Kari', price: 35000 },
            { name: 'Nasi Goreng Ayam', price: 30000 },
            { name: 'Nasi Goreng Seafood', price: 35000 },
            { name: 'Nasi Goreng Cabe Ijo', price: 30000 },
            { name: 'Nasi Goreng Kambing', price: 30000 },
            { name: 'Nasi Goreng Pete', price: 35000 },
            { name: 'Nasi Goreng Tomyam Seafood', price: 35000 },
            { name: 'Nasi Goreng Special', price: 37500 },
            { name: 'Nasi Goreng Ayam Lada Hitam', price: 40000 },
            { name: 'Nasi Goreng Daging Lada Hitam', price: 40000 },
            { name: 'Nasi Goreng Bistik Daging', price: 27500 },
            { name: 'Nasi Goreng Sate Kecap', price: 27500 },
        ]
    },
    {
        name: 'Olahan Mie',
        items: [
            { name: 'Mie Goreng/Kuah', price: 30000 },
            { name: 'Mie Goreng/Kuah Seafood', price: 30000 },
            { name: 'Mie Goreng/Kuah Special', price: 35000 },
            { name: 'Mihun Goreng/Kuah', price: 30000 },
            { name: 'Mihun Goreng/Kuah Seafood', price: 30000 },
            { name: 'Mihun Goreng/Kuah Special', price: 35000 },
            { name: 'Kwetiaw Goreng/Kuah', price: 30000 },
            { name: 'Kwetiaw Goreng/Kuah Seafood', price: 30000 },
            { name: 'Kwetiaw Goreng/Kuah Special', price: 35000 },
            { name: 'Ifumie Goreng/Kuah', price: 30000 },
            { name: 'Ifumie Goreng/Kuah Seafood', price: 30000 },
            { name: 'Ifumie Goreng/Kuah Special', price: 35000 },
            { name: 'Indomie Kuah/Goreng', price: 25000 },
            { name: 'Indomie Kuah/Goreng Special', price: 30000 },
            { name: 'Indomie Kuah/Goreng Seafood', price: 35000 },
            { name: 'Mie Daging Lada Hitam', price: 40000 },
            { name: 'Indomie Daging Lada Hitam', price: 37500 },
            { name: 'Indomie Kari Bangladesh', price: 15000 },
            { name: 'Indomie Kari Bangladesh (Ayam)', price: 27000 },
        ]
    },
     {
        name: 'Steak',
        items: [
            { name: 'Single Chicken Steak', price: 25000 },
            { name: 'Double Chicken Steak', price: 40000 },
            { name: 'Steak Tenderloin', price: 40000 },
            { name: 'Crispy Steak Tenderloin', price: 40000 },
        ]
    },
    {
        name: 'Snack/Cemilan',
        items: [
            { name: 'Roti Cane Gula', price: 10000 },
            { name: 'Roti Kuah Kari', price: 12500 },
            { name: 'Roti Cane Coklat Keju', price: 15000 },
            { name: 'Roti Cane Susu', price: 12500 },
            { name: 'Mie Rebus', price: 20000 },
            { name: 'Martabak Telur', price: 20000 },
            { name: 'Martabak Mesir', price: 27500 },
            { name: 'Kari Kambing Kecil', price: 30000 },
            { name: 'Kari Kambing Besar', price: 40000 },
            { name: 'Kentang Goreng', price: 20000 },
            { name: 'Ubi Goreng', price: 15000 },
            { name: 'Tahu & Tempe Goreng', price: 18000 },
            { name: 'Pisang Bakar Cokelat Keju', price: 21000 },
            { name: 'Pisang Goreng Cokelat Keju', price: 22000 },
            { name: 'Pisang Goreng Srikaya', price: 20000 },
            { name: 'Mantau Srikaya', price: 21000 },
            { name: 'Jamur Crispy', price: 20000 },
            { name: 'Nugget', price: 20000 },
            { name: 'Sosis', price: 20000 },
        ]
    },
    {
        name: 'Minuman (Tea/Ice Cream/Coffee)',
        items: [
            { name: 'Hot Tea', price: 6000 },
            { name: 'Iced Tea', price: 10000 },
            { name: 'Hot Lemon Tea', price: 10000 },
            { name: 'Iced Lemon Tea', price: 15000 },
            { name: 'Teh Jahe Sereh', price: 15000 },
            { name: 'Teh Mint', price: 15000 },
            { name: 'Teh Jahe Panas', price: 15000 },
            { name: 'Hot Milo', price: 15000 },
            { name: 'Iced Milo', price: 20000 },
            { name: 'Teh Tarik', price: 20000 },
            { name: 'Teh Jahe Susu Panas', price: 20000 },
            { name: 'Coffee Brown Sugar', price: 20000 },
            { name: 'Coffee Lemonade', price: 25000 },
        ]
    },
    {
        name: 'Special Drink',
        items: [
            { name: 'Es Kelapa Gelas', price: 20000 },
            { name: 'Es Kelapa Bulat', price: 20000 },
            { name: 'Es Kelapa Jeruk', price: 25000 },
            { name: 'Es Vanilla Coffee Latte', price: 25000 },
            { name: 'Es Mocca Coffee Latte', price: 25000 },
            { name: 'Es Macchiato', price: 25000 },
            { name: 'Matcha', price: 25000 },
            { name: 'Chocolate Frappe', price: 25000 },
            { name: 'Jus Pelangi', price: 27500 },
            { name: 'Sop Buah', price: 25000 },
            { name: 'Es Buah', price: 25000 },
            { name: 'Ice Lychee Tea', price: 20000 },
        ]
    },
    {
        name: 'Fresh Juice',
        items: [
            { name: 'Jus Alpukat', price: 20000 },
            { name: 'Jus Kuini', price: 20000 },
            { name: 'Jus Jeruk', price: 20000 },
            { name: 'Jus Markisa', price: 20000 },
            { name: 'Jus Terong Belanda', price: 20000 },
            { name: 'Jus Belimbing', price: 20000 },
            { name: 'Jus Semangka', price: 20000 },
            { name: 'Jus Nanas', price: 20000 },
            { name: 'Jus Timun', price: 20000 },
            { name: 'Jus Apel', price: 20000 },
            { name: 'Jus Wortel', price: 20000 },
            { name: 'Jus Pepaya', price: 20000 },
            { name: 'Jus Tomat', price: 20000 },
            { name: 'Jus Sirsak', price: 25000 },
            { name: 'Jus Buah Naga', price: 20000 },
            { name: 'Jus Sawi Nanas', price: 25000 },
            { name: 'Jus Martabe', price: 25000 },
            { name: 'Jus Jambu Merah', price: 25000 },
            { name: 'Jus Wortel Susu', price: 25000 },
            { name: 'Jus Sirsak Naga', price: 27500 },
        ]
    },
    {
        name: 'Mocktail',
        items: [
            { name: 'Rainbow Mocktail', price: 20000 },
            { name: 'Dragon Mocktail', price: 20000 },
            { name: 'Green Blue', price: 20000 },
            { name: 'Strawberry Lemon', price: 20000 },
            { name: 'Orange Blue', price: 20000 },
            { name: 'Anggur Mint', price: 20000 },
            { name: 'Leci Mocktail', price: 20000 },
            { name: 'Strawberry Leci', price: 20000 },
            { name: 'Lemon Madu', price: 20000 },
            { name: 'Lemon Selasih', price: 20000 },
            { name: 'India Mocktail', price: 20000 },
            { name: 'Sexy Blue', price: 20000 },
            { name: 'Sunkiest Mojito', price: 20000 },
        ]
    }
];